#!/bin/bash

./node_modules/sass/sass.js --no-source-map --quiet --load-path=node_modules/govuk-elements-sass/public/sass --load-path=node_modules/govuk_frontend_toolkit/stylesheets app/assets/sass/application.scss app/public/stylesheets/application.css
./node_modules/sass/sass.js --no-source-map --quiet --load-path=node_modules/govuk-elements-sass/public/sass --load-path=node_modules/govuk_frontend_toolkit/stylesheets app/assets/sass/application-ie8.scss app/public/stylesheets/application-ie8.css
