module.exports = {
  LOGGING_PATH: process.env.LOGGING_PATH,
  // DB
  DATABASE_SERVER: process.env.APVS_DATABASE_SERVER,
  DATABASE: process.env.APVS_DATABASE,
  EXT_WEB_USERNAME: process.env.APVS_EXT_WEB_USERNAME,
  EXT_WEB_PASSWORD: process.env.APVS_EXT_WEB_PASSWORD,
  EXT_MIGRATION_USERNAME: process.env.APVS_EXT_MIGRATION_USERNAME,
  EXT_MIGRATION_PASSWORD: process.env.APVS_EXT_MIGRATION_PASSWORD,
  // i18n
  I18N_UPDATEFILES: process.env.I18N_UPDATEFILES
}
