apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: help-with-prison-visits-external
version: 0.2.0

dependencies:
  - name: generic-service
    version: 1.0.9
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: clamav
    version: "0.1.x"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
