module.exports = {
  SEND_CLAIM_NOTIFICATION: 'SEND-CLAIM-NOTIFICATION',
  COMPLETE_CLAIM: 'COMPLETE-CLAIM',
  REQUEST_INFORMATION_RESPONSE_SUBMITTED_NOTIFICATION: 'REQUEST-INFORMATION-RESPONSE-SUBMITTED-NOTIFICATION',
  REQUEST_INFORMATION_RESPONSE: 'REQUEST-INFORMATION-RESPONSE',
  SEND_MALWARE_ALERT: 'SEND-MALWARE-ALERT',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
  TECHNICAL_HELP_SUBMITTED: 'TECHNICAL_HELP_SUBMITTED'
}
