module.exports = {
  SEND_CLAIM_NOTIFICATION: 'SEND-CLAIM-NOTIFICATION',
  COMPLETE_CLAIM: 'COMPLETE-CLAIM',
  REQUEST_INFORMATION_RESPONSE_SUBMITTED_NOTIFICATION: 'REQUEST-INFORMATION-RESPONSE-SUBMITTED-NOTIFICATION',
  REQUEST_INFORMATION_RESPONSE: 'REQUEST-INFORMATION-RESPONSE',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED'
}
