module.exports = {
  COMPLETE_CLAIM: 'COMPLETE-CLAIM',
  REQUEST_INFORMATION_RESPONSE: 'REQUEST-INFORMATION-RESPONSE',
  SEND_MALWARE_ALERT: 'SEND-MALWARE-ALERT',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
  REFERENCE_RECOVERY: 'REFERENCE_RECOVERY',
}
