---
# Environment specific values, override helm_deploy/help-with-prison-visits-external/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "help-with-prison-visits.service.gov.uk"
    tlsSecretName: "help-with-prison-visits-service-cert"
  env:
    APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits.service.justice.gov.uk'
    APVS_MAINTENANCE_MODE: 'true'

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits
