# Environment specific values, override helm_deploy/help-with-prison-visits-external/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "help-with-prison-visits-preprod.hmpps.service.justice.gov.uk"
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS,setvar:tx.paranoia_level=3"
      # Block Detectify scanner with 418
      SecRule REQUEST_HEADERS:User-Agent "@pm detectify Detectify DETECTIFY" "id:800003,phase:1,deny,status:418,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  env:
    FEATURES_YCS_JOURNEY: 'true'
    ENVIRONMENT_NAME: preprod

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits-devtest
